image:
  repository: avatar-service
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: avatar-service.local

serviceMonitor:
  enabled: false

prometheusRule:
  enabled: false

postgresql:
  password: avatars
  sslmode: disable

rabbitmq:
  username: guest
  password: guest
