{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatar-service.fullname" . }}-rabbitmq
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  selector:
    {{- include "avatar-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: metrics
      port: 15692
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avatar-service.fullname" . }}-rabbitmq
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "avatar-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "avatar-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image | quote }}
          command: ["sh", "-c", "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"]
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
            - name: metrics
              containerPort: 15692
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password | quote }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
{{- end }}
