apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "avatar-service.fullname" . }}-worker
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "avatar-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "avatar-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "avatar-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["worker"]
          ports:
            - name: metrics
              containerPort: 9091
          envFrom:
            - configMapRef:
                name: {{ include "avatar-service.fullname" . }}-config
            - secretRef:
                name: {{ include "avatar-service.fullname" . }}-secret
          env:
            - name: SERVICE_NAME
              value: "avatar-service-worker"
            - name: METRICS_ADDR
              value: ":9091"
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
