{{- if .Values.hpa.server.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "avatar-service.fullname" . }}-server
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "avatar-service.fullname" . }}-server
  minReplicas: {{ .Values.hpa.server.minReplicas }}
  maxReplicas: {{ .Values.hpa.server.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.server.cpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.server.memoryAverageUtilization }}
{{- end }}
---
{{- if .Values.hpa.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "avatar-service.fullname" . }}-worker
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "avatar-service.fullname" . }}-worker
  minReplicas: {{ .Values.hpa.worker.minReplicas }}
  maxReplicas: {{ .Values.hpa.worker.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.worker.cpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.worker.memoryAverageUtilization }}
{{- end }}
