apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "avatar-service.fullname" . }}-migrate
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  {{- if .Values.migrations.hook }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "avatar-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "avatar-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - 'until avatars-service migrate status; do echo "waiting for postgres"; sleep 2; done'
          envFrom:
            - secretRef:
                name: {{ include "avatar-service.fullname" . }}-secret
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate", "up"]
          envFrom:
            - secretRef:
                name: {{ include "avatar-service.fullname" . }}-secret
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
