{{- include "avatar-service.validateCredentials" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avatar-service.fullname" . }}-secret
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DSN: {{ include "avatar-service.postgresDsn" . | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secret.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secret.minioSecretKey | quote }}
  RABBITMQ_URL: {{ include "avatar-service.rabbitmqUrl" . | quote }}
