apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatar-service.fullname" . }}-server
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "avatar-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatar-service.fullname" . }}-worker
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    {{- include "avatar-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
